### ISSUE TITLE
Need proper error message for incorrect certificate backend path

### ISSUE THREAD

**Issue by vignesh97** [BlueMedoraPublic/bmcert#15]
```
VAULT_CERT_URL=https://vault.example.localnet:8200/v1/my-pki-int
./bmcert create --hostname test-ci.example.localnet --format cert --tls-skip-verify -O /Users/vignesh/Downloads
````
The current output is 
```
Vault response status: 404 Not Found
Response Body: {"errors":["1 error occurred:\n\t* unsupported path\n\n"]}
```
Please update with proper error message.

**Comment by jsirianni** [comment]
also ```
~/go/src/bmcert
❯ export VAULT_CERT_URL=fake

~/go/src/bmcert
❯ ./bmcert create --hostname test.bluemedora.localnet
fake returned 0```

**Comment by jsirianni** [comment]
resolved https://github.com/BlueMedoraPublic/bmcert/commit/b3457e12bee9048f04204ad47301aea74ab01ba9
